#!/bin/bash

path="/dv/hdfs/inbound/InboundTest/table1"

declare -a arr=("grpg")

hiveConnectString="'jdbc:hive2://avula1.com:2181,avula2.com:2181,avula3.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2'"

dbName="avula_in"

## now loop through the above array
for i in "${arr[@]}"
do
   echo "Creating table " ${i}
   schemaPath=${path}
   dataPath=${path}${i}

   hiveSQL="create external table ${dbName}.${i} stored as avro location '${dataPath}/test/09-Oct-2017 23.45.55 PM/input/'  TBLPROPERTIES('avro.schema.url'='${schemaPath}/schema/AutoGeneratedSchema.avsc')"

   beeline -u -S "${hiveConnectString}" -e "${hiveSQL}"
done
echo "Table Creation Done"
